dev:
	npx vite dev

build:
	npx vite build

check:
	npx svelte-kit sync
	npx svelte-check --tsconfig ./tsconfig.json

check.watch:
	npx svelte-kit sync
	npx svelte-check --tsconfig ./tsconfig.json --watch
